name: CI
on:
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_PASSWORD: pg_pwd
      POSTGRES_USER: ci_test
      POSTGRES_DB: postgres
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
          POSTGRES_USER: ${{env.POSTGRES_USER}}
          POSTGRES_DB: ${{env.POSTGRES_DB}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2
      - run: deno install && cd test && deno install
      - name: Test
        run: deno task test
        env:
          PG_URL: pg://${{env.POSTGRES_USER}}:${{env.POSTGRES_PASSWORD}}@127.0.0.1:5432/${{env.POSTGRES_DB}}
        working-directory: ./test
