name: CI
on:
  push:
    branches:
      - "*"
      - "*/*"
    paths:
      - src/**
      - test/**
      - sql/**
      - .github/workflows/ci.yaml
      - deno.json
      - deno.lock
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ci_test
      POSTGRES_DB: postgres
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: ${{env.POSTGRES_USER}}
          POSTGRES_DB: ${{env.POSTGRES_DB}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2
      - run: deno install
      - name: Test
        run: deno task test
        env:
          PG_URL: pg://${{env.POSTGRES_USER}}@127.0.0.1:5432/${{env.POSTGRES_DB}}
        working-directory: ./test
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2
      - run: deno task check-fmt
      - run: deno install
      - run: deno task check-type
